version: 1.0.{build}
branches:
  only:
  - master
  - dev
skip_tags: true
matrix:
  fast_finish: true 
image: Visual Studio 2019
environment:
  azure-relay-dotnet/ClientSecret:
    secure: /8H7C81iNS+gVi7LhJCEOPUlNaa30y4KcY4nw/g2C4HGxOv6SrcroyDvMnqD+5GN
  azure-relay-dotnet/TenantId:
    secure: xohonz/X8PPLOVIdT3ch2C5XeSa30RwR6NuXFh4e85svXT1mJNGGO1HQEGxCk3wp
  azure-relay-dotnet/AppId:
    secure: c+H140oRJfHtmFHZxSRLWocv5AU0q33X7kgMcTcXxhJvtVhk2WAk1dRQkSN+SyoA
  matrix:
    - DotNetRunTime: netcoreapp2.1
      azure-relay-dotnet/CodeCovSecret:
        secure: NAlk4Em1NARlJqd8aan0jD8SW8iE86quYwiBi2ngs5Dfl0gYuwDuZaSkpoFFf2Cz
skip_commits:
  files:
    - '**/*.md'
artifacts:
- path: '**\Microsoft.Azure.Relay*.dll'
build_script:
- ps: .\build\build.ps1
test: off
