name: azure-relay-dotnet

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-windows:
    name: Build 'azure-relay-dotnet' on windows-latest

    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v1
    - run: dotnet --info
    - name: Restore
      run: .\restore.cmd
    - name: Build
      run: .\build.cmd
    - name: Package
      run: .\package.cmd
    - name: Test
      run: .\test.cmd
      env:
        RELAY_CONNECTION_STRING: ${{ secrets.RELAY_CONNECTION_STRING }}

  build-nix:
    strategy:
      matrix:
        platform: [ 'ubuntu-latest', 'macos-latest' ]
    name: Build 'azure-relay-dotnet' on ${{ matrix.platform }}

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 2.2.402
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.402'
    - name: Setup .NET Core 3.0.100
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: copy .NET Core 2.2.402
      run: |
        rsync -a ${DOTNET_ROOT}/../../2.2.402/x64/shared/ $DOTNET_ROOT/shared
    - run: dotnet --info
    - name: Configure Execute Permission
      run: chmod a+rx *.sh
    - run: ls -l
    - name: Restore
      run: ./restore.sh
    - name: Build
      run: ./build.sh
    - name: Package
      run: ./package.sh
