name: azure-relay-dotnet

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '**\*.md'
  pull_request:
    branches:
      - master
      - dev
    paths-ignore:
      - '**\*.md'

jobs:
  build-windows:
    name: Build on windows-latest
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        global-json-file: global.json
    - run: dotnet --info
    - name: Restore
      run: .\restore.cmd
    - name: Build
      run: .\build.cmd
    - name: Package
      run: .\package.cmd

  build-nix:
    strategy:
      matrix:
        platform: [ 'ubuntu-latest', 'macos-latest' ]

    name: Build on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        global-json-file: global.json
    - run: dotnet --info
    - name: Restore
      run: ./restore.sh
    - name: Build
      run: ./build.sh
    - name: Package
      run: ./package.sh
